config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :user_studies
      resources :user_works

      root to: "users#index"
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "users#index"

  resources :users, only: [:index, :show] do
    member do
      get :studies
      get :works
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_works
  has_many :user_studies

  broadcasts_refreshes
end

app/models/user_study.rb
class UserStudy < ApplicationRecord
  belongs_to :user

  broadcasts_refreshes
end

app/models/user_work.rb
class UserWork < ApplicationRecord
  belongs_to :user

  broadcasts_refreshes
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/user_studies_controller.rb
module Admin
  class UserStudiesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/user_works_controller.rb
module Admin
  class UserWorksController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.includes(:user_studies, :user_works).find(params[:id])
  end

  def works
   @user = User.includes(:user_works).find(params[:id])
  end

  def studies
    @user = User.includes(:user_studies).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboCv</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
     <meta name="view-transition" content="same-origin" />
    <%= turbo_refreshes_with method: :morph, scroll: :preserve %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/user_studies/_user_study.html.erb
<div class="mb-2">
  <p class="font-semibold">Degree:</p>
  <p><%= study.name %></p>
</div>
<div class="mb-2">
  <p class="font-semibold">Institution:</p>
  <p><%= study.school_name %></p>
</div>
<div class="mb-2">
  <p class="font-semibold">Year:</p>
  <p><%= study.started_at %> to <%= study.finished_at || 'current' %></p>
</div>

app/views/user_works/_user_work.html.erb
<div class="mb-2">
  <p class="font-semibold">Position:</p>
  <p><%= work.title %></p>
</div>
<div class="mb-2">
  <p class="font-semibold">Company:</p>
  <p><%= work.company_name %></p>
</div>
<div class="mb-2">
  <p class="font-semibold">Duration:</p>
  <p><%= work.started_at %> to <%= work.finished_at || 'current' %></p>
</div>
<div class="mb-2">
  <p class="font-semibold">Responsibilities:</p>
  <p><%= work.description %></p>
</div>

app/views/users/_contact.html.erb
<aside class="col-span-4 bg-blue-600 rounded-lg text-white p-10 mb-3 ml-3">
  <h2 class="text-lg font-semibold mb-2">Contact Information</h2>
  <p class="mb-2">Location: <%= user.location %></p>
  <p class="mb-2">Phone: <%= user.phone_number %></p>
  <p class="mb-2">Email: <%= user.email %></p>
  <p class="mb-2">LinkedIn: <a href="https://www.linkedin.com/in/alejandro-lopez-b49795ba/">alejandro-lopez-b49795ba</a></p>
  <p class="mb-2">Github: <a href="https://github.com/alejolopez91">alejolopez91</a></p>
</aside>

app/views/users/_user.html.erb
<div class="flex flex-row" id="main">
  <div class="bg-gray-800 p-6 rounded-lg shadow-md mb-3" id="<%= dom_id(@user) %>">
    <h1 class="text-3xl font-semibold mb-4"><%= @user.full_name %></h1>
    <p class="text-gray-400 mb-4">Fullstack Developer</p>
    <p class="text-gray-400 mb-4"><%= @user.introduction %></p>
    <hr class="my-4 border-gray-700">
  </div>
  <%= render partial: 'users/contact', locals: { user: @user }  %>
</div>

app/views/users/index.html.erb
<body class="bg-gray-900 text-white font-sans">
  <div class="flex flex-col">
  <h2>Users<h2>
  <% @users.each do |user| %>
    <%= link_to user.full_name, user_path(user) %>
  <% end %>
</body>

app/views/users/show.html.erb
<body class="bg-gray-900 text-white font-sans">
  <div class="mx-auto px-4 py-8">
    <%= turbo_stream_from @user %>
    <%= render @user %>
    <%= link_to 'Back', users_path %>
    <%= link_to 'Studies', studies_user_path(@user), data: { turbo_stream: true } %>
    <%= link_to 'Experience', works_user_path(@user), data: { turbo_stream: true } %>
  </div>
</body>

app/views/users/studies.html.erb
<body class="bg-gray-900 text-white font-sans">
  <div class="mx-auto px-4 py-8">
    <div class="bg-gray-800 p-6 rounded-lg shadow-md mb-3" id="main">
      <div>
        <h2 class="text-lg font-semibold mb-2">Education</h2>
        <% @user.user_studies.each do |study| %>
          <%= turbo_stream_from study %>
          <%= render study, study: study %>
        <% end %>
      </div>
    </div>
    <%= link_to 'Back', user_path(@user) %>
  </div>
</body>

app/views/users/works.html.erb
<body class="bg-gray-900 text-white font-sans">
  <div class="mx-auto px-4 py-8">
    <div class="bg-gray-800 p-6 rounded-lg shadow-md mb-3" id="main">
      <div>
        <h2 class="text-lg font-semibold mb-2">Experience</h2>
        <% @user.user_works.each do |work| %>
          <%= turbo_stream_from work %>
          <%= render work, work: work %>
        <% end %>
      </div>
    </div>
    <%= link_to 'Back', user_path(@user) %>
  </div>
</body>